-- ============================================
-- TODO管理テーブル (Oracle Database)
-- ============================================

-- テーブル削除
DROP TABLE IF EXISTS TODOS;

-- テーブル作成
CREATE TABLE TODOS (
    ID              NUMBER(10)      NOT NULL,
    TITLE           VARCHAR2(200)   NOT NULL,
    DESCRIPTION     CLOB            NOT NULL,
    CATEGORY        VARCHAR2(50),
    PRIORITY        NUMBER(1)       DEFAULT 2 NOT NULL,
    STATUS          NUMBER(1)       DEFAULT 0 NOT NULL,
    DUE_DATE        DATE,
    CREATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_AT      TIMESTAMP       DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT PK_TODOS PRIMARY KEY (ID)
);

-- コメント
COMMENT ON TABLE TODOS IS 'TODO管理';
COMMENT ON COLUMN TODOS.ID IS 'ID';
COMMENT ON COLUMN TODOS.TITLE IS 'タイトル';
COMMENT ON COLUMN TODOS.DESCRIPTION IS '詳細';
COMMENT ON COLUMN TODOS.CATEGORY IS 'カテゴリ';
COMMENT ON COLUMN TODOS.PRIORITY IS '優先度 (1:低, 2:中, 3:高)';
COMMENT ON COLUMN TODOS.STATUS IS 'ステータス (0:未着手, 1:進行中, 2:完了)';
COMMENT ON COLUMN TODOS.DUE_DATE IS '期限日';
COMMENT ON COLUMN TODOS.CREATED_AT IS '作成日時';
COMMENT ON COLUMN TODOS.UPDATED_AT IS '更新日時';

-- テストデータ
INSERT INTO TODOS (ID, TITLE, DESCRIPTION, CATEGORY, PRIORITY, STATUS, DUE_DATE, CREATED_AT, UPDATED_AT) VALUES (1, '週次レポート作成', '先週の進捗をまとめて報告書を作成する', '業務', 3, 2, TO_DATE('2025-06-14', 'YYYY-MM-DD'), TO_TIMESTAMP('2025-06-10 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-06-14 17:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO TODOS (ID, TITLE, DESCRIPTION, CATEGORY, PRIORITY, STATUS, DUE_DATE, CREATED_AT, UPDATED_AT) VALUES (2, 'ミーティング資料準備', '月曜の定例会議用のスライドを作成', '業務', 3, 1, TO_DATE('2025-06-17', 'YYYY-MM-DD'), TO_TIMESTAMP('2025-06-12 10:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-06-15 14:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO TODOS (ID, TITLE, DESCRIPTION, CATEGORY, PRIORITY, STATUS, DUE_DATE, CREATED_AT, UPDATED_AT) VALUES (3, 'メール返信', '取引先からの問い合わせに回答する', '連絡', 2, 0, TO_DATE('2025-06-18', 'YYYY-MM-DD'), TO_TIMESTAMP('2025-06-14 11:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-06-14 11:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO TODOS (ID, TITLE, DESCRIPTION, CATEGORY, PRIORITY, STATUS, DUE_DATE, CREATED_AT, UPDATED_AT) VALUES (4, '経費精算', '出張費の精算処理を行う', '経理', 1, 0, TO_DATE('2025-06-28', 'YYYY-MM-DD'), TO_TIMESTAMP('2025-06-10 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-06-10 09:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO TODOS (ID, TITLE, DESCRIPTION, CATEGORY, PRIORITY, STATUS, DUE_DATE, CREATED_AT, UPDATED_AT) VALUES (5, 'システム設計書レビュー', '新機能の設計書を確認してフィードバック', '開発', 2, 1, TO_DATE('2025-06-20', 'YYYY-MM-DD'), TO_TIMESTAMP('2025-06-13 15:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-06-17 10:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO TODOS (ID, TITLE, DESCRIPTION, CATEGORY, PRIORITY, STATUS, DUE_DATE, CREATED_AT, UPDATED_AT) VALUES (6, 'テストデータ作成', '結合テスト用のデータを準備する', '開発', 2, 0, TO_DATE('2025-06-21', 'YYYY-MM-DD'), TO_TIMESTAMP('2025-06-15 09:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-06-15 09:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO TODOS (ID, TITLE, DESCRIPTION, CATEGORY, PRIORITY, STATUS, DUE_DATE, CREATED_AT, UPDATED_AT) VALUES (7, 'バグ修正 #1234', 'ログイン画面のバリデーションエラー対応', '開発', 3, 2, TO_DATE('2025-06-12', 'YYYY-MM-DD'), TO_TIMESTAMP('2025-06-11 08:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-06-12 16:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO TODOS (ID, TITLE, DESCRIPTION, CATEGORY, PRIORITY, STATUS, DUE_DATE, CREATED_AT, UPDATED_AT) VALUES (8, 'ドキュメント更新', 'API仕様書に新エンドポイントを追記', 'その他', 1, 0, TO_DATE('2025-07-01', 'YYYY-MM-DD'), TO_TIMESTAMP('2025-06-14 13:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_TIMESTAMP('2025-06-14 13:00:00', 'YYYY-MM-DD HH24:MI:SS'));

COMMIT;

-- 確認
SELECT * FROM TODOS ORDER BY ID;
